name: oua_flutter33
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  #DI
  get_it: ^7.2.0

  #FİREBASE
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_storage: ^12.1.0

  #STATE_MANAGEMENT
  stacked: ^3.0.1
  stacked_services: ^0.9.5

  #Loader
  loader_overlay: ^4.0.0

  #File Picker
  file_picker: ^8.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  stacked_generator: ^1.4.0
  build_runner: ^2.4.11  

flutter:
  uses-material-design: true
  assets:
   - assets/
